# Generated by Django 4.2.3 on 2023-08-07 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Universe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the universe', max_length=255)),
                ('description', models.TextField(help_text='Description of the universe')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created time')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Modified time')),
                ('allowed_users', models.ManyToManyField(help_text='Allowed users', related_name='allowed_universes', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(help_text='Owner of the universe', on_delete=django.db.models.deletion.CASCADE, related_name='owned_universes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WikiDocument',
            fields=[
                ('id', models.AutoField(help_text='Primary key', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the document', max_length=255)),
                ('description', models.TextField(help_text='Description of the document')),
                ('version', models.IntegerField(default=0, help_text='Version of the document')),
                ('document_type', models.CharField(choices=[('CHARACTER', 'Character'), ('PLOT', 'Plot'), ('SETTING', 'Setting'), ('ITEM', 'Item'), ('OTHER', 'Other')], help_text='Type of the document', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created time')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Modified time')),
                ('is_published', models.BooleanField(default=False, help_text='Is published')),
                ('is_deleted', models.BooleanField(default=False, help_text='Is deleted')),
                ('owner', models.ForeignKey(help_text='Owner of the document', on_delete=django.db.models.deletion.CASCADE, related_name='owned_objects', to=settings.AUTH_USER_MODEL)),
                ('related_documents', models.ManyToManyField(blank=True, help_text='Related documents', to='wiki.wikidocument')),
                ('universe', models.ForeignKey(help_text='Universe of the document', on_delete=django.db.models.deletion.CASCADE, to='wiki.universe')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
