# Generated by Django 4.2.2 on 2023-06-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikidocument',
            name='related_documents',
            field=models.ManyToManyField(blank=True, to='wiki.wikidocument'),
        ),
    ]
