# Generated by Django 4.2.2 on 2023-07-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_alter_wikidocument_related_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universe',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wikidocument',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
